apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: zaytcevcom/go-msa:1.0.6
          ports:
            - containerPort: 8000
          command: [ "sh", "-c", "./opt/app/bin --config configs/demo/config.json" ]
          volumeMounts:
            - name: config-volume
              mountPath: /configs/demo
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: demo-config