apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.demo.name }}
  labels:
    app: {{ .Values.demo.name }}
spec:
  selector:
    app: {{ .Values.demo.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.demo.ports.http }}
      targetPort: {{ .Values.demo.ports.http }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.demo.ports.metrics }}
      targetPort: {{ .Values.demo.ports.metrics }}