{
 "title": "Demo dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Ingress stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "App stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Response time",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, uri) (rate(http_server_requests_seconds_bucket{uri=~\"/user/.*\"}[1m])))",
     "legendFormat": "[0.5] {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, uri) (rate(http_server_requests_seconds_bucket{uri=~\"/user/.*\"}[1m])))",
     "legendFormat": "[0.95] {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, uri) (rate(http_server_requests_seconds_bucket{uri=~\"/user/.*\"}[1m])))",
     "legendFormat": "[0.99] {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.9999, sum by(le, uri) (rate(http_server_requests_seconds_bucket{uri=~\"/user/.*\"}[1m])))",
     "legendFormat": "[0.9999] {{uri}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_sum{uri=~\"/user/.*\"}[1m])) /\nsum by(uri) (rate(http_server_requests_seconds_count{uri=~\"/user/.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_requests_total{status=~\"5.+\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}