apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-deployment
spec:
  replicas: {{ .Values.billing.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.billing.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.billing.name }}
    spec:
      containers:
        - name: {{ .Values.billing.name }}
          image: "{{ .Values.billing.image.repository }}:{{ .Values.billing.image.version }}"
          command: ["sh", "-c", "{{ .Values.billing.startCommand }}"]
          volumeMounts:
            - name: config-volume
              mountPath: /configs/billing
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.billing.ports.http }}
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: billing-config