version: '3.9'
services:

  demo:
    container_name: demo
    build:
      context: ../..
      dockerfile: ./build/demo/Dockerfile
    restart: always
    volumes:
      - ../../configs/demo:/configs/demo
    command: sh -c "./opt/app/bin --config configs/demo/config.json"
    ports:
      - "8000:8000"
    networks:
      - demo_network

networks:
  demo_network:
    driver: bridge