version: '3.9'
services:

  demo:
    container_name: demo
    build:
      context: ../..
      dockerfile: ./build/demo/Dockerfile
    restart: always
    volumes:
      - ../../configs/demo:/configs/demo
    command: sh -c "./opt/app/bin --config configs/demo/config.json"
    ports:
      - "8000:8000"
    networks:
      - demo_network

  postgres:
    image: postgres:13
    container_name: demo_postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ../../scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ../../var/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - demo_network

networks:
  demo_network:
    driver: bridge