demo:
  name: demo
  replicaCount: 3
  image:
    repository: zaytcevcom/go-msa
    version: 1.0.6
  ports:
    http: 8000
    metrics: 9093
  startCommand: "./opt/app/bin --config configs/demo/config.json"
migrations:
  name: demo-migrations
  image:
    repository: zaytcevcom/go-msa-migrations
    version: 1.0.6